export const cartState = {
    CartTotal: {
        ApartmentShipFee: 0,
        ApartmentShipFeeBeforeDiscount: 0,
        CouponDiscount: 0,
        ShipFee: 0,
        ShipFeeBase: 0,
        ShipFeeDiscount: 0,
        SumTotal: 17000,
        Total: 17100,
        TotalBillPromotion: 0,
        TotalDiscount: 0,
        TotalFresh: 0,
        TotalNonExpiredFree: 17100,
        TotalVoucherAfter: 0,
        VoucherDiscount: 0
    },
    Cart: {
        CartId: 'BFD6A4AACAAC267064158FA33FE5C18BF3DDDBFD46CCB2B9D2CF48F903823401',
        ListCartItem: [
            {
                OutputTypeId: 0,
                POSSubGroupId: 3023,
                Price: 17100,
                ProgramEmail: null,
                ProgramGameType: 0,
                ProgramLogId: 0,
                ProgramLogType: 0,
                ProgramName: '',
                ProgramPhone: null,
                ProgramUserId: 0,
                PromotionComboId: 0,
                PromotionId: 0,
                PromotionListGroupId: null,
                PromotionMessage: null,
                PromotionType: 0,
                Quantity: 1,
                QuantityCondition: 0,
                QuantityMessage: null,
                QuantityNew: 1,
                QuantityPromotionId: 0,
                RecommendCartId: 0,
                ShipPackageTypeId: 0,
                ShowGender: false,
                StoreId: 6463,
                SysPrice: 19000,
                SystemNote: null,
                Total: 17100,
                TypeProduct: 0,
                Unit: 'chai',
                Info: {
                    BrandName: 'Coca Cola',
                    CategoryId: 2443,
                    CategoryName: 'Nước ngọt, giải khát',
                    Color: null,
                    ExpiredInfo: '',
                    GACategoryName: 'Nước ngọt, giải khát',
                    Id: 196828,
                    Image: 'https://cdn.tgdd.vn/Products/images/2443/196828/bhx/nuoc-ngot-coca-cola-zero-15-lit-201903181312204664_300x300.jpg',
                    IsExpiredCoolProduct: false,
                    IsFresh: false,
                    IsFreshExpired: false,
                    IsPreOrder: false,
                    ManufactureId: 2561,
                    Name: 'Nước ngọt hương chanh Coca Cola Zero 1.5 lít',
                    PreDate: null,
                    ProductCode: '9892850000395',
                    QuantityInCart: 0,
                    RootCategoryId: 2488,
                    ShortName: 'Nước ngọt Coca Cola Zero 1.5 lít',
                    Size: null,
                    Url: '/nuoc-ngot/coca-cola-zero-1-5-lit'
                }
            }
        ],
        ListCartItemBuy: [],
        ListCartItemOff: []
    }
};
