export const EMPTY_PHONE = 'Vui lòng nhập số điện thoại!';
export const INVALID_PHONE = 'Số điện thoại không đúng định dạng!';
export const EMPTY_CUSNAME = 'Vui lòng nhập họ và tên!';
export const OUTOFRANGE_CUSNAME = 'Họ và tên quá dài, vui lòng nhập lại!';
export const EMPTY_SHIPADDRESS = 'Vui lòng nhập địa chỉ!';
export const OUTOFRANGE_SHIPADDRESS = 'Địa chỉ quá dài, vui lòng nhập lại!';
export const ERR_PROVINCE = 'Vui lòng chọn tỉnh thành!';
export const ERR_DISTRICT = 'Vui lòng chọn quận huyện!';
export const ERR_WARD = 'Vui lòng chọn phường, xã!';
