export const categoryState = {
    Info: {
        $id: '3',
        Id: 2443,
        Name: 'Nước ngọt, giải khát',
        Url: 'nuoc-ngot',
        Icon: 'nuoc-ngot-2111201814128.png',
        Labels: [21394, 21395],
        Filter: [18972, 17779],
        ListPropertyTicketId: [],
        ParentIds: [2488],
        ParentName: null,
        RelatedIds: [3226],
        IsLeaf: true,
        DisplayOrder: 2,
        CategoryIdsTwoInOne: [],
        Quantity: 0,
        SEOTitle:
            'Nước ngọt, nước tăng lực, nước giải khát đa dạng nhiều thương hiệu',
        SEOKeywords:
            'nước ngọt,nước ngọt có ga,nước giải khát,nước tăng lực,nước uống',
        SEODescription:
            'Hàng trăm sản phẩm nước ngọt, nước tăng lực, nước trà, nước giải khát với nhiều thương hiệu như Coca, Pepsi, 7up,... với nhiều ưu đãi hấp dẫn tại Bách Hóa XANH.',
        SEOInfobox:
            '<a href="https://www.bachhoaxanh.com/nuoc-ngot" name="Nước ngọt chính hãng tại Bách Hoá XANH" target="_self" title="Nước ngọt chính hãng tại Bách Hoá XANH">Nước ngọt</a>, <strong>nước ngọt có ga</strong> hay còn được gọi là<strong> nước giải khát có ga</strong> là loại nước thường chứa cácbon điôxít bão hòa, chất làm ngọt, và thường có thêm hương liệu. Một số nước giải khát có ga khác còn chứa caffeine, phẩm màu, chất bảo quản và các thành phần khác được kiểm định an toàn cho sức khỏe.<br /><br />Hiện có <strong>rất nhiều thương hiệu nước ngọt nổi tiếng tại Việt Nam</strong> như <a href="https://www.bachhoaxanh.com/nuoc-ngot-coca-cola" name="CocaCola chính hãng tại Bách Hoá XANH" target="_blank" title="CocaCola chính hãng tại Bách Hoá XANH">Coca Cola</a>, <a href="https://www.bachhoaxanh.com/nuoc-ngot-pepsi" name="Pepsi chính hãng tại Bách Hoá XANH" target="_blank" title="Pepsi chính hãng tại Bách Hoá XANH">Pepsi</a>, <a href="https://www.bachhoaxanh.com/nuoc-ngot-fanta" name="Fanta chính hãng tại Bách Hoá XANH" target="_blank" title="Fanta chính hãng tại Bách Hoá XANH">Fanta</a>, <a href="https://www.bachhoaxanh.com/nuoc-ngot-mirinda" name="Mirinda chính hãng tại Bách Hoá XANH" target="_blank" title="Mirinda chính hãng tại Bách Hoá XANH">Mirinda</a>, <a href="https://www.bachhoaxanh.com/nuoc-ngot-7-up" name="7 up chính hãng tại Bách Hoá XANH" target="_blank" title="7 up chính hãng tại Bách Hoá XANH">7 up</a>,... cùng nhiều thương hiệu khác cũng rất được người dùng ưa chuộng và chọn mua.<br /><br />Nước ngọt được dùng để <strong>giải khát nhanh hay dùng chung trong các bữa tiệc</strong>. Với lượng ga mạnh cùng khả năng kích thích vị giác, người dùng sẽ <strong>cảm thấy ngon miệng hơn khi ăn uống</strong> cùng bạn bè và gia đình.<br /><br />Ngoài nước ngọt ra nước giải khát còn có thêm những biến thể khác như <a href="https://www.bachhoaxanh.com/nuoc-ngot-nuoc-tang-luc" name="Nước tăng lực chính hãng Bách Hoá XANH" target="_blank" title="Nước tăng lực chính hãng Bách Hoá XANH">nước tăng lực</a>, <a href="https://www.bachhoaxanh.com/nuoc-ngot-bu-khoang" name="Nước bù khoáng, nước uống trong thể thao" target="_blank" title="Nước bù khoáng, nước uống trong thể thao">nước bù khoáng</a> hay thậm chí là nước uống thảo dược giúp bổ dung dưỡng chất và tăng cường sức khoẻ.',
        ReturnPolicy: '',
        VideoUrl: '',
        IsRefund: 0,
        VirtualChildCateIds: null,
        ValueIDFilterList: [],
        ValueIDFilterNameList: null,
        IsVirtualCate: false
    },
    Brands: [
        {
            Id: 2561,
            Name: 'Coca Cola',
            Logo: 'Coca-Cola2443-s_32.png',
            Url: 'coca-cola',
            BelongTo: 0,
            DisplayOrder: 1,
            LinkShare: '',
            VideoUrl: null,
            Description:
                'Coca Cola là thương hiệu <a href="https://www.bachhoaxanh.com/nuoc-ngot">đồ uống có gas</a> được yêu thích hiện nay thuộc Công ty Coca Cola. Với các thành phần giải khát hoàn toàn tự nhiên, <a href="https://www.bachhoaxanh.com/nuoc-ngot-coca-cola">nước ngọt Coca Cola</a> mang đến cho bạn thức uống với hương vị đặc trưng giúp bạn giải khát tức thời, cung cấp cho bạn nguồn năng lượng tích cực sảng khoái để bạn hoạt động. Bên cạnh đó, Coca-Cola còn cho ra đời 2 dòng sản phẩm là <a href="https://www.bachhoaxanh.com/nuoc-ngot/nuoc-ngot-khong-duong-coca-cola-light-lon-330ml">Coca-Cola Light</a> với đặc điểm không đường dành cho người ăn kiêng và <a href="https://www.bachhoaxanh.com/nuoc-ngot/nuoc-ngot-coke-zero-sleek-lon-330ml">Coca Zero</a> sử dụng đường Sucralose giúp cơ thể bạn có thể kiểm soát lượng đường mà mình hấp thụ.',
            RelatedBrandIds: null,
            OEMBrandIds: [6488]
        },
        {
            Id: 4716,
            Name: 'Pepsi',
            Logo: 'Pepsi2443-s_37.png',
            Url: 'pepsi',
            BelongTo: 0,
            DisplayOrder: 2,
            LinkShare: '',
            VideoUrl: null,
            Description:
                'Pepsi - một trong những thương hiệu <a href="https://www.bachhoaxanh.com/nuoc-ngot">nước ngọt </a>nổi tiếng được sản xuất bởi PepsiCo. Với hương vị thơm ngon cùng những thành phần nguyên liệu an toàn giúp tạo nên một thức uống giải khát giúp bù đắp nước cho cơ thể, xua tan đi cảm giác mệt mỏi, tạo năng lượng hứng khởi để hoạt động tích cực trong ngày dài. Bên cạnh đó, <a href="https://www.bachhoaxanh.com/nuoc-ngot-pepsi">nước ngọt Pepsi</a> không chứa các thành phần hoá chất độc hại nên rất an toàn cho sức khoẻ người tiêu dùng.',
            RelatedBrandIds: null,
            OEMBrandIds: [4259]
        }
    ],
    Filters: [
        {
            ProductPropValueBOLst: [
                {
                    $id: '9',
                    ValueID: 135963,
                    PropertyID: 18972,
                    Value: 'Nước ngọt',
                    DisplayOrder: 1,
                    CountProduct: 0,
                    IsSearch: false,
                    CompareValue: 0,
                    Icon: null,
                    IsActived: false,
                    ActivedDate: null,
                    ActivedUser: null,
                    IsDeleted: false,
                    DeletedDate: null,
                    DeletedUser: null,
                    CreatedDate: null,
                    CreatedUser: null,
                    UpdatedDate: null,
                    UpdatedUser: null,
                    IsExistPro: false,
                    IsSelected: false,
                    IsExist: true,
                    ValueData: 0,
                    IconUrl: null,
                    URL: null,
                    DMURL: null,
                    Description: null,
                    Listsiteid: null,
                    MetaTitle:
                        'Mua nước ngọt có ga các loại tại BachhoaXANH.com',
                    MetaDescription: null,
                    IconScale: 0,
                    ManuNameList: null,
                    GeneralCategoryId: 0,
                    GeneralPropertyId: null,
                    GeneralBoxName: null,
                    URLFilter: null
                },
                {
                    $id: '10',
                    ValueID: 135964,
                    PropertyID: 18972,
                    Value: 'Nước tăng lực',
                    DisplayOrder: 2,
                    CountProduct: 0,
                    IsSearch: false,
                    CompareValue: 0,
                    Icon: null,
                    IsActived: false,
                    ActivedDate: null,
                    ActivedUser: null,
                    IsDeleted: false,
                    DeletedDate: null,
                    DeletedUser: null,
                    CreatedDate: null,
                    CreatedUser: null,
                    UpdatedDate: null,
                    UpdatedUser: null,
                    IsExistPro: false,
                    IsSelected: false,
                    IsExist: true,
                    ValueData: 0,
                    IconUrl: null,
                    URL: null,
                    DMURL: null,
                    Description: null,
                    Listsiteid: null,
                    MetaTitle: 'Mua nước tăng lực giá tốt tại BachhoaXANH.com',
                    MetaDescription: null,
                    IconScale: 0,
                    ManuNameList: null,
                    GeneralCategoryId: 0,
                    GeneralPropertyId: null,
                    GeneralBoxName: null,
                    URLFilter: null
                },
                {
                    $id: '11',
                    ValueID: 151010,
                    PropertyID: 18972,
                    Value: 'Cà phê',
                    DisplayOrder: 3,
                    CountProduct: 0,
                    IsSearch: false,
                    CompareValue: 0,
                    Icon: null,
                    IsActived: false,
                    ActivedDate: null,
                    ActivedUser: null,
                    IsDeleted: false,
                    DeletedDate: null,
                    DeletedUser: null,
                    CreatedDate: null,
                    CreatedUser: null,
                    UpdatedDate: null,
                    UpdatedUser: null,
                    IsExistPro: false,
                    IsSelected: false,
                    IsExist: true,
                    ValueData: 0,
                    IconUrl: null,
                    URL: null,
                    DMURL: null,
                    Description: null,
                    Listsiteid: null,
                    MetaTitle: null,
                    MetaDescription: null,
                    IconScale: 0,
                    ManuNameList: null,
                    GeneralCategoryId: 0,
                    GeneralPropertyId: null,
                    GeneralBoxName: null,
                    URLFilter: null
                },
                {
                    $id: '12',
                    ValueID: 135966,
                    PropertyID: 18972,
                    Value: 'Trà',
                    DisplayOrder: 3,
                    CountProduct: 0,
                    IsSearch: false,
                    CompareValue: 0,
                    Icon: null,
                    IsActived: false,
                    ActivedDate: null,
                    ActivedUser: null,
                    IsDeleted: false,
                    DeletedDate: null,
                    DeletedUser: null,
                    CreatedDate: null,
                    CreatedUser: null,
                    UpdatedDate: null,
                    UpdatedUser: null,
                    IsExistPro: false,
                    IsSelected: false,
                    IsExist: true,
                    ValueData: 0,
                    IconUrl: null,
                    URL: null,
                    DMURL: null,
                    Description: null,
                    Listsiteid: null,
                    MetaTitle:
                        'Mua nước trà giải khát giá tốt tại BachhoaXANH.com',
                    MetaDescription: null,
                    IconScale: 0,
                    ManuNameList: null,
                    GeneralCategoryId: 0,
                    GeneralPropertyId: null,
                    GeneralBoxName: null,
                    URLFilter: null
                },
                {
                    $id: '13',
                    ValueID: 150885,
                    PropertyID: 18972,
                    Value: 'Trà sữa',
                    DisplayOrder: 4,
                    CountProduct: 0,
                    IsSearch: false,
                    CompareValue: 0,
                    Icon: null,
                    IsActived: false,
                    ActivedDate: null,
                    ActivedUser: null,
                    IsDeleted: false,
                    DeletedDate: null,
                    DeletedUser: null,
                    CreatedDate: null,
                    CreatedUser: null,
                    UpdatedDate: null,
                    UpdatedUser: null,
                    IsExistPro: false,
                    IsSelected: false,
                    IsExist: true,
                    ValueData: 0,
                    IconUrl: null,
                    URL: null,
                    DMURL: null,
                    Description: null,
                    Listsiteid: null,
                    MetaTitle: null,
                    MetaDescription: null,
                    IconScale: 0,
                    ManuNameList: null,
                    GeneralCategoryId: 0,
                    GeneralPropertyId: null,
                    GeneralBoxName: null,
                    URLFilter: null
                },
                {
                    $id: '14',
                    ValueID: 135969,
                    PropertyID: 18972,
                    Value: 'Nước thảo dược',
                    DisplayOrder: 5,
                    CountProduct: 0,
                    IsSearch: false,
                    CompareValue: 0,
                    Icon: null,
                    IsActived: false,
                    ActivedDate: null,
                    ActivedUser: null,
                    IsDeleted: false,
                    DeletedDate: null,
                    DeletedUser: null,
                    CreatedDate: null,
                    CreatedUser: null,
                    UpdatedDate: null,
                    UpdatedUser: null,
                    IsExistPro: false,
                    IsSelected: false,
                    IsExist: true,
                    ValueData: 0,
                    IconUrl: null,
                    URL: null,
                    DMURL: null,
                    Description: null,
                    Listsiteid: null,
                    MetaTitle:
                        'Mua nước uống thảo dược tốt cho sức khoẻ tại BachhoaXANH.com',
                    MetaDescription: null,
                    IconScale: 0,
                    ManuNameList: null,
                    GeneralCategoryId: 0,
                    GeneralPropertyId: null,
                    GeneralBoxName: null,
                    URLFilter: null
                },
                {
                    $id: '15',
                    ValueID: 136221,
                    PropertyID: 18972,
                    Value: 'Nước trái cây',
                    DisplayOrder: 6,
                    CountProduct: 0,
                    IsSearch: false,
                    CompareValue: 0,
                    Icon: null,
                    IsActived: false,
                    ActivedDate: null,
                    ActivedUser: null,
                    IsDeleted: false,
                    DeletedDate: null,
                    DeletedUser: null,
                    CreatedDate: null,
                    CreatedUser: null,
                    UpdatedDate: null,
                    UpdatedUser: null,
                    IsExistPro: false,
                    IsSelected: false,
                    IsExist: true,
                    ValueData: 0,
                    IconUrl: null,
                    URL: null,
                    DMURL: null,
                    Description: null,
                    Listsiteid: null,
                    MetaTitle:
                        'Mua nước trái cây giá tốt nhiều khuyến mãi tại bachhoaxanh.com',
                    MetaDescription: null,
                    IconScale: 0,
                    ManuNameList: null,
                    GeneralCategoryId: 0,
                    GeneralPropertyId: null,
                    GeneralBoxName: null,
                    URLFilter: null
                },
                {
                    $id: '16',
                    ValueID: 137798,
                    PropertyID: 18972,
                    Value: 'Nước bù khoáng',
                    DisplayOrder: 7,
                    CountProduct: 0,
                    IsSearch: false,
                    CompareValue: 0,
                    Icon: null,
                    IsActived: false,
                    ActivedDate: null,
                    ActivedUser: null,
                    IsDeleted: false,
                    DeletedDate: null,
                    DeletedUser: null,
                    CreatedDate: null,
                    CreatedUser: null,
                    UpdatedDate: null,
                    UpdatedUser: null,
                    IsExistPro: false,
                    IsSelected: false,
                    IsExist: true,
                    ValueData: 0,
                    IconUrl: null,
                    URL: null,
                    DMURL: null,
                    Description: null,
                    Listsiteid: null,
                    MetaTitle:
                        'Mua nước bù khoáng, nước thể thao giá tốt tại BachhoaXANH.com',
                    MetaDescription: null,
                    IconScale: 0,
                    ManuNameList: null,
                    GeneralCategoryId: 0,
                    GeneralPropertyId: null,
                    GeneralBoxName: null,
                    URLFilter: null
                }
            ],
            PropertyID: 18972,
            GroupID: 0,
            GroupOrder: 0,
            PropertyName: 'Loại',
            GroupName: null,
            Description: null,
            PropertyType: 0,
            IsGeneral: false,
            IsTooltip: false,
            DisplayOrder: 0,
            IsActived: false,
            ActivedDate: null,
            ActivedUser: null,
            IsDeleted: false,
            DeletedDate: null,
            DeletedUser: null,
            CreatedDate: null,
            CreatedUser: null,
            UpdatedDate: null,
            UpdatedUser: null,
            IsGencol: false,
            IsSearch: false,
            IsOperator: false,
            IsSelected: false,
            IsSpecial: false,
            IsExist: true,
            Value: null,
            CategoryID: 0,
            AdvisorLink: null,
            AdvisorText: null,
            PropertyWeight: 0,
            IsShortConfig: false,
            ShortConfigOrder: 0,
            ListSiteID: null,
            MetaTitle: null,
            MetaDescription: null,
            PropIsSearch: false
        },
        {
            ProductPropValueBOLst: [
                {
                    $id: '18',
                    ValueID: 124495,
                    PropertyID: 17779,
                    Value: 'Thùng',
                    DisplayOrder: 1,
                    CountProduct: 0,
                    IsSearch: false,
                    CompareValue: 0,
                    Icon: null,
                    IsActived: false,
                    ActivedDate: null,
                    ActivedUser: null,
                    IsDeleted: false,
                    DeletedDate: null,
                    DeletedUser: null,
                    CreatedDate: null,
                    CreatedUser: null,
                    UpdatedDate: null,
                    UpdatedUser: null,
                    IsExistPro: false,
                    IsSelected: false,
                    IsExist: true,
                    ValueData: 0,
                    IconUrl: null,
                    URL: null,
                    DMURL: null,
                    Description: null,
                    Listsiteid: null,
                    MetaTitle: null,
                    MetaDescription: null,
                    IconScale: 0,
                    ManuNameList: null,
                    GeneralCategoryId: 0,
                    GeneralPropertyId: null,
                    GeneralBoxName: null,
                    URLFilter: null
                },
                {
                    $id: '19',
                    ValueID: 124494,
                    PropertyID: 17779,
                    Value: 'Lốc',
                    DisplayOrder: 1,
                    CountProduct: 0,
                    IsSearch: false,
                    CompareValue: 0,
                    Icon: null,
                    IsActived: false,
                    ActivedDate: null,
                    ActivedUser: null,
                    IsDeleted: false,
                    DeletedDate: null,
                    DeletedUser: null,
                    CreatedDate: null,
                    CreatedUser: null,
                    UpdatedDate: null,
                    UpdatedUser: null,
                    IsExistPro: false,
                    IsSelected: false,
                    IsExist: true,
                    ValueData: 0,
                    IconUrl: null,
                    URL: null,
                    DMURL: null,
                    Description: null,
                    Listsiteid: null,
                    MetaTitle: null,
                    MetaDescription: null,
                    IconScale: 0,
                    ManuNameList: null,
                    GeneralCategoryId: 0,
                    GeneralPropertyId: null,
                    GeneralBoxName: null,
                    URLFilter: null
                },
                {
                    $id: '20',
                    ValueID: 149374,
                    PropertyID: 17779,
                    Value: 'Chai lớn',
                    DisplayOrder: 2,
                    CountProduct: 0,
                    IsSearch: false,
                    CompareValue: 0,
                    Icon: null,
                    IsActived: false,
                    ActivedDate: null,
                    ActivedUser: null,
                    IsDeleted: false,
                    DeletedDate: null,
                    DeletedUser: null,
                    CreatedDate: null,
                    CreatedUser: null,
                    UpdatedDate: null,
                    UpdatedUser: null,
                    IsExistPro: false,
                    IsSelected: false,
                    IsExist: true,
                    ValueData: 0,
                    IconUrl: null,
                    URL: null,
                    DMURL: null,
                    Description: null,
                    Listsiteid: null,
                    MetaTitle: null,
                    MetaDescription: null,
                    IconScale: 0,
                    ManuNameList: null,
                    GeneralCategoryId: 0,
                    GeneralPropertyId: null,
                    GeneralBoxName: null,
                    URLFilter: null
                }
            ],
            PropertyID: 17779,
            GroupID: 0,
            GroupOrder: 0,
            PropertyName: 'Đóng gói',
            GroupName: null,
            Description: null,
            PropertyType: 0,
            IsGeneral: false,
            IsTooltip: false,
            DisplayOrder: 0,
            IsActived: false,
            ActivedDate: null,
            ActivedUser: null,
            IsDeleted: false,
            DeletedDate: null,
            DeletedUser: null,
            CreatedDate: null,
            CreatedUser: null,
            UpdatedDate: null,
            UpdatedUser: null,
            IsGencol: false,
            IsSearch: false,
            IsOperator: false,
            IsSelected: false,
            IsSpecial: false,
            IsExist: true,
            Value: null,
            CategoryID: 0,
            AdvisorLink: null,
            AdvisorText: null,
            PropertyWeight: 0,
            IsShortConfig: false,
            ShortConfigOrder: 0,
            ListSiteID: null,
            MetaTitle: null,
            MetaDescription: null,
            PropIsSearch: false
        }
    ],
    CurrentData: {
        Products: [],
        Total: 0,
        TotalPromotion: 0
    }
};
